BookMyShowClone/BookMyShowClone/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views as main_views
from movie_app import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    path('', main_views.HomePage.as_view(), name = 'home'),
    path("signup/", views.SignUp.as_view(), name="signup"),
    path('thanks/', main_views.Thanks.as_view(), name = 'thanks'),
    path('admin/', admin.site.urls),
    path("movies/", include("movie_app.urls")),
    path("movies/", include("django.contrib.auth.urls")),
    path("logout/", views.user_logout, name="logout"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

BookMyShowClone/movie_app/urls.py
from django.urls import path
from . import views

app_name = 'movie_app'

urlpatterns = [
    path('NotEnough/', views.NotEnough.as_view(), name="NotEnough"),
    path('shows/', views.MovieListView, name = 'current_shows'),
    path('shows/<int:pk>/', views.show_times, name='movie_shows'),
    path('shows/<int:pk>/book', views.show_seats, name='seats'),
    path('shows/<int:pk>/payments', views.payments, name = 'payments'),
    path('my_tickets/', views.booked_tickets, name='my_tickets'),
    path("login/", views.Loginview, name='login'),
]

BookMyShowClone/movie_app/models.py
from django.db import models
from django.contrib import auth
from django.contrib.auth import get_user_model

# Create your models here.

class User(auth.models.User, auth.models.PermissionsMixin):
    def __str__(self):
        return str(self.username)

class Movie(models.Model):
    poster = models.ImageField(null=True, upload_to='movie_posters')
    thumbnail = models.ImageField(null=True, upload_to='movie_thumbnails')
    name = models.CharField(max_length=50, unique = True)
    released_date = models.DateField()
    language = models.CharField(max_length=20, default='English')
    length = models.TimeField(default = '02:00:00')

    def __str__(self):
        return self.name

class Hall(models.Model):
    name = models.CharField(max_length=50, unique = True)
    location = models.CharField(max_length=80)
    vip_no = models.PositiveIntegerField(null = True)
    gold_no = models.PositiveIntegerField(null = True)
    platinum_no = models.PositiveIntegerField(null = True)
    silver_no = models.PositiveIntegerField(null = True)
    vip_price = models.FloatField(null = True)
    gold_price = models.FloatField(null = True)
    platinum_price = models.FloatField(null = True)
    silver_price = models.FloatField(null = True)

    def __str__(self):
        return self.name

class Show(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, null = True)
    hall = models.ForeignKey(Hall, on_delete=models.CASCADE, null = True)
    show_time = models.DateTimeField(null = True)
    vip_left = models.PositiveIntegerField(null = True)
    gold_left = models.PositiveIntegerField(null = True)
    silver_left = models.PositiveIntegerField(null = True)
    platinum_left = models.PositiveIntegerField(null = True)

    def __str__(self):
        return str(self.movie.name) + " at " + str(self.hall.name)

class Bought_ticket(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    show = models.ForeignKey(Show, on_delete=models.CASCADE)
    total_amount = models.FloatField(null = True)
    ticket_type = models.CharField(null=True, max_length=10)
    no_of_tickets = models.PositiveIntegerField(default=1)
    paid = models.BooleanField(default=False)

    def __str__(self):
        return str(self.user.username) + " booked tickets for " + str(self.show.movie.name) + " Paid: " + str(self.paid)

BookMyShowClone/movie_app/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

BookMyShowClone/movie_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import login, logout, authenticate, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy,reverse
from django.views.generic import CreateView, ListView, TemplateView
from . import forms, models
from django.http import HttpResponse, HttpResponseRedirect

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "movie_app/signup.html"


class NotEnough(TemplateView):
    template_name = "movie_app/not_enough.html"


def Loginview(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request, user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse("movie_app:current_shows"))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")
    else:
        #Nothing has been provided for username or password.
        return render(request, 'movie_app/login.html', {})

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('thanks'))

@login_required
def MovieListView(request):
    movie_list = models.Movie.objects.all()
    return render(request, 'movie_app/movies_showing.html', {'movie_list':movie_list, 'breaks':(0, 3, 6, 9)})

@login_required
def show_times(request, pk):
    movie = get_object_or_404(models.Movie, pk=pk)
    halls = models.Hall.objects.all()
    shows_one = movie.show_set.filter(hall = halls[0])
    if shows_one.exists() == False:
        shows_one = None
    shows_two = movie.show_set.filter(hall = halls[1])
    if shows_two.exists() == False:
        shows_two = None
    shows_three = movie.show_set.filter(hall = halls[2])
    if shows_three.exists() == False:
        shows_three = None
    return render(request, 'movie_app/movie_detail.html', {'shows_one':shows_one, 
                                                           'shows_two':shows_two, 
                                                           'shows_three':shows_three, 
                                                           'movie':movie})

@login_required
def show_seats(request, pk):
    show = get_object_or_404(models.Show, pk=pk)
    if request.method == "POST":
        ticket_type = request.POST.get("type_radio")
        ticket_no = request.POST.get("no_of_ticket")
        if ticket_type=="VIP":
            if int(ticket_no)>show.vip_left:
                return HttpResponseRedirect(reverse("movie_app:NotEnough"))
            ticket_price = show.hall.vip_price
        elif ticket_type=="Platinum":
            if int(ticket_no)>show.platinum_left:
                return HttpResponseRedirect(reverse("movie_app:NotEnough"))
            ticket_price = show.hall.platinum_price
        elif ticket_type=="Gold":
            if int(ticket_no)>show.gold_left:
                return HttpResponseRedirect(reverse("movie_app:NotEnough"))
            ticket_price = show.hall.gold_price
        elif ticket_type=="Silver":
            if int(ticket_no)>show.silver_left:
                return HttpResponseRedirect(reverse("movie_app:NotEnough"))
            ticket_price = show.hall.silver_price
        total = float(ticket_price) * int(ticket_no)
        user = get_user_model().objects.get(id=request.user.id)
        b = models.Bought_ticket.objects.create(user = user, show = show, total_amount = total,ticket_type = ticket_type, no_of_tickets = ticket_no)
        b.save()
        return render(request, "movie_app/show_seats.html", {'show':show,'total':total, 'ticket_no': ticket_no, 'ticket_price': ticket_price})

    return render(request, 'movie_app/show_seats.html', {'show':show})

@login_required
def payments(request, pk):
    tickets = models.Bought_ticket.objects.order_by("-pk")[0]
    if request.method == "POST":
        payment_method = request.POST.get("payment_method")
        tickets.paid = True
        if tickets.ticket_type == "VIP":
            tickets.show.vip_left = tickets.show.vip_left - tickets.no_of_tickets
        elif tickets.ticket_type == "Platinum":
            tickets.show.platinum_left -= tickets.no_of_tickets
        elif tickets.ticket_type == "Gold":
            tickets.show.gold_left -= tickets.no_of_tickets
        elif tickets.ticket_type == "Silver":
            tickets.show.silver_left -= tickets.no_of_tickets
        tickets.show.save()
        tickets.save()
        return render(request, 'movie_app/payments.html', {'tickets':tickets, 'payment_method':payment_method})
    return render(request, 'movie_app/payments.html', {'tickets':tickets})

@login_required
def booked_tickets(request):
    user = get_user_model().objects.get(id = request.user.id)
    tickets = user.bought_ticket_set.all()
    if(len(tickets)==0):
        return render(request, "movie_app/my_tickets.html")
    return render(request, "movie_app/my_tickets.html", {'tickets':tickets})

BookMyShowClone/templates/movie_app/login.html
{% extends 'base.html' %}

{% block content %}
<hr>
    <div class="jumbotron">
        <h1>Login</h1>
        <form action="{% url 'movie_app:login' %}" method="POST">
            {% csrf_token %}
            <p>Username:</p>
            <input type="text" name='username' placeholder="Enter username"><br><br>
            <p>Password:</p>
            <input type="password" name="password" ><br><br>
            <input type="submit" value="Login" class="btn btn-outline-success btn-sm">
        </form>
    </div> 
{% endblock %}

BookMyShowClone/templates/movie_app/movie_detail.html
{% extends "base.html" %}

{% block content %}
<hr>
  <div class="jumbotron myjumbo" style="background-image:url('{{ movie.poster.url }}');">
    <div class="bottomleft">
        <hr> <hr> <hr> <hr> <hr> <hr> <hr> <hr> <hr> <hr> <hr> <hr>
        <strong>Movie:</strong> &nbsp;
        <strong>{{movie.name}}</strong>
        <br>
        <strong>Released date: </strong> &nbsp; &nbsp; {{ movie.released_date }}
        <br>
        <strong>Language: </strong> &nbsp; &nbsp; {{movie.language}}
        <br>
        <strong>Movie length: </strong> &nbsp; &nbsp; {{movie.length.hour}} hours {{movie.length.minute}} mins
    </div>

  </div>
  <div class="mycontent">
   
    <p><h5><strong>Shows Available: </strong></h5></p>

    {% if shows_one != None %}
      <p>
          <strong>Grand Cines: </strong> <br>
          <a href="https://www.google.com/maps/place/Grande+Cines/@26.1798992,91.7492039,17z/data=!3m1!4b1!4m5!3m4!1s0x375a5a297531bd2b:0x85a93a4fdc6c8156!8m2!3d26.1798944!4d91.7513926"
             target="_blank">
          Location: Grand Plaza, 5th Floor, G.S. Road, Paltan Bazar, Guwahati, Assam 781008, India
          </a>
          <br> <br>
              {% for show in shows_one %}
                <a class="btn btn-outline-success" href="{% url 'movie_app:seats' pk=show.pk %}"> {{show.show_time.time}} </a> &nbsp; &nbsp;
              {% endfor %} 
      </p> <br>
    {% endif %}
      <br>
    {% if shows_two != None %}
      <p>
          <strong>Carnival Cinemas: Beltola: </strong> <br>
          <a href="https://www.google.com/maps/place/PVR:+City+Center,+Guwahati/@26.1584367,91.771434,15.64z/data=!4m8!1m2!2m1!1spvr+near+City+Center,+GS+Road,+Ganeshguri,+Guwahati,+Assam!3m4!1s0x375a59eacc1a2107:0xf5d07af6b7a78e3b!8m2!3d26.1544855!4d91.781361"
             target="_blank">
             Location: Christian Basti, G.S. Road, Guwahati, Assam 781005, India
          </a>
          <br> <br>
              {% for show in shows_two %}
                <a class="btn btn-outline-success" href="{% url 'movie_app:seats' pk=show.pk %}"> {{show.show_time.time}} </a> &nbsp; &nbsp;
              {% endfor %}      
      </p> <br>
    {% endif %}
      <br>
    {% if shows_three != None %}
      <p>
          <strong>PVR: City Center: </strong> <br>
          <a href="https://www.google.com/maps/place/Carnival+Cinemas/@26.1202477,91.7959522,17z/data=!3m1!4b1!4m5!3m4!1s0x375a5f4c31dce8f3:0xd2e4ec2e22996e05!8m2!3d26.1202429!4d91.7981409"
             target="_blank">
             Location: Beltola-Basistha Road, Beltola, Guwahati, Assam 781028, India
          </a>
          <br> <br>
              {% for show in shows_three %}
                <a class="btn btn-outline-success" href="{% url 'movie_app:seats' pk=show.pk %}"> {{show.show_time.time}} </a> &nbsp; &nbsp;
              {% endfor %} 
      </p> <br>
    {% endif %}

  

  </div>
{% endblock %}

BookMyShowClone/templates/movie_app/movies_showing.html
{% extends "base.html" %}

{% block content %}
<hr>
<hr>
<div class="mycontent">

  <h3>Current movies are: </h3><br><br>

        <table class="table table-borderless mytable">
            <tr>
                {% for movie in movie_list %}
                
                    {% if forloop.counter0 in breaks %}
                        </tr>
                        <tr>
                    {% endif %}
                    <td>
                        <a style="font-size: 1.2em;" href="{% url 'movie_app:movie_shows' pk=movie.pk %}">
                            <img class="img-fluid img-thumbnail" src="{{ movie.thumbnail.url }}" alt="Something went wrong" height="300px" width="150px">
                            <br>
                            <strong>{{movie.name}}</strong><br>
                        </a>
                        {{movie.language}}
                    </td>
                {% endfor %}
            </tr>
        </table>    
</div>

{% endblock%}

BookMyShowClone/templates/movie_app/my_tickets.html
{% extends "base.html" %}

{% block content %}
<hr>
  {% if tickets %}
    <div class="mycontent">
        <h5><strong>Your purchased tickets are: </strong></h5><hr>
    </div>
    
    {% for ticket in tickets %}
        {% if ticket.paid == True %}
            <div class="jumbotron myjumbo" style="background-image:url('{{ ticket.show.movie.poster.url }}'); border: 3px solid white;">
              <div class="bottomleft">
                <hr> <hr> <hr> <hr> <hr> <hr> <hr> <hr>
                <strong>Movie: </strong>{{ticket.show.movie.name}} <br>
                <strong>Hall: </strong>{{ticket.show.hall.name}} <br>
                <strong>Language: </strong>{{ticket.show.movie.language}} <br>
                <strong>Movie Length: </strong>{{ticket.show.movie.length.hour}} hours {{ticket.show.movie.length.minute}} mins <br>
                <strong>Movie time: </strong>{{ticket.show.show_time.time}} <br>
                <strong>Total price: </strong>{{ticket.total_amount}} Rs.<br>
                <strong>No. of tickets: </strong>{{ticket.no_of_tickets}} <br>
              </div>  
            </div>
        {% endif %}
    {% endfor %}
        
  {% else %}
    <div class="jumbotron">
        <h5>You haven't bought any tickets!!!</h5>
        <br>
        <br>
        <p><strong>Buy some: &nbsp; &nbsp; &nbsp; <a class="btn btn-outline-info btn-sm" href="{% url 'movie_app:current_shows' %}">Movies</a> </strong></p>
    </div>
  {% endif %}
  <hr>
{% endblock %}

BookMyShowClone/templates/movie_app/not_enough.html
{% extends "base.html" %}

{% block content %}
  <strong>
    <h5>Sorry!!!</h5>
    <br>
    <br>
    <p>The requested no of tickets is more than available tickets!!!</p>
  </strong> 
  <hr>
{% endblock %}

BookMyShowClone/templates/movie_app/payments.html
{% extends "base.html" %}

{% block content %}
    <hr>
    <div class='jumbotron anojumbo'>
      <table class="table table-borderless" style="margin: auto; color: white;">
          <tr>
            <th>
                <strong>Movie: </strong>{{tickets.show.movie.name}} <br>
                <strong>Hall: </strong>{{tickets.show.hall.name}} <br>
                <strong>Language: </strong>{{tickets.show.movie.language}} <br>
                <strong>Movie time: </strong>{{tickets.show.show_time.time}} <br>
                <strong>Total price: </strong>{{tickets.total_amount}} Rs.<br>
                <strong>No. of tickets: </strong>{{tickets.no_of_tickets}} <br>
            </th>
            <th>
              <div style="text-align: right;">
                  <img class="img-fluid img-thumbnail myimg" src="{{ tickets.show.movie.thumbnail.url }}" alt="Something went wrong" height="350px" width="175px">
              </div>
            </th>
          </tr>
      </table>
    </div>
    <div class="mycontent">
        {% if payment_method %}
            <script lang='javascipt'>
              alert("After choosing your payment method you will be asked to provide the detailed information about your credit card or debit card or your UPI client. After that you will get the following...");
            </script>
          
          <p><strong>
              You have paid: {{tickets.total_amount}} Rs. 
              <br>
              <br>
              Your Booking is done!
          </p>
            <br>
            <br>
          <h4>Thank You!</h4>
            <br>
            <br>
          </strong>

          <p>Go to Current movies: &nbsp; &nbsp;
          <a class="btn btn-sm btn-info" href="{% url 'movie_app:current_shows' %}">Shows</a></p>

          <p>Go to Your Tickets: &nbsp; &nbsp;
          <a class="btn btn-sm btn-info" href="{% url 'movie_app:my_tickets' %}">My Tickets</a></p>

        {% else %}
        <h5>Select a Payment Method:</h5>
        <br>
        <form method="POST">
            {% csrf_token %}
            <input type="radio" value="c_card" name="payment_method"> Credit Card<br>
            <input type="radio" value="d_card" name="payment_method"> Debit Card<br>
            <input type="radio" value="upi" name="payment_method"> UPI<br>
            <br>
            <div class="center">
              <input class="btn btn-outline-success btn-lg" type="submit" value="PAY">
            </div>
        </form>
        {% endif %}    
        <hr>
    </div>
{% endblock %}

BookMyShowClone/templates/movie_app/show_seats.html
{% extends "base.html" %}
  
{% block content %}
<hr>
  <div class='jumbotron anojumbo'>
    <table class="table table-borderless" style="margin: auto; color: white;">
          <tr>
              <td>
                  <strong>Movie: </strong>{{show.movie.name}} <br>
                  <strong>Hall: </strong>{{show.hall.name}} <br>
                  <strong>Language: </strong>{{show.movie.language}} <br>
                  <strong>Movie time: </strong>{{show.show_time.time}} <br>
              </td>
              <td>
                  <div style="text-align: right;">
                      <img class="img-fluid img-thumbnail myimg" src="{{ show.movie.thumbnail.url }}" alt="Something went wrong">
                  </div>
              </td>
            </tr> 
    </table>
  </div>
  
  <div class="mycontent">


    {% if total %}
      <hr>
      <pre style="color:aliceblue; text-align: center;" ><h5><strong>

        Ticket(x1)                  {{ticket_price}}
        No. of Tickets:                 {{ticket_no}}
        ---------------------------------
        Total(x{{ticket_no}})                   {{total}}
      </strong></h5></pre>
      <br>
      <div class="center">
          <a class="btn btn-outline-success btn-lg" href="{% url 'movie_app:payments' pk=show.pk %}">PAY</a>
      </div>
    {% else %}
      <h5>BOOK YOUR TICKETS BELOW: </h5>
    <form action="#" method="POST">
      {% csrf_token %}
      <div class="mycontainer">
        <hr>
          &nbsp; &nbsp; <input type="radio" name="type_radio" value="VIP">
          &nbsp; &nbsp; &nbsp; &nbsp; VIP tickets:
          &nbsp; &nbsp; &nbsp; &nbsp; Total: {{show.hall.vip_no}}
          &nbsp; &nbsp; &nbsp; &nbsp; Left: {{show.vip_left}}
          &nbsp; &nbsp; &nbsp; &nbsp; Price: {{show.hall.vip_price}} Rs.
        <hr>    
      </div>
      <div class="mycontainer">
        <hr>
          &nbsp; &nbsp; <input type="radio" name="type_radio" value="Platinum">
          &nbsp; &nbsp; &nbsp; &nbsp; Platinum tickets:
          &nbsp; &nbsp; &nbsp; &nbsp; Total: {{show.hall.platinum_no}}
          &nbsp; &nbsp; &nbsp; &nbsp; Left: {{show.platinum_left}}
          &nbsp; &nbsp; &nbsp; &nbsp; Price: {{show.hall.platinum_price}}
        <hr>
      </div>
      <div class="mycontainer">
        <hr>
          &nbsp; &nbsp; <input type="radio" name="type_radio" value="Gold">
          &nbsp; &nbsp; &nbsp; &nbsp; Gold tickets:
          &nbsp; &nbsp; &nbsp; &nbsp; Total: {{show.hall.gold_no}}
          &nbsp; &nbsp; &nbsp; &nbsp; Left: {{show.gold_left}}
          &nbsp; &nbsp; &nbsp; &nbsp; Price: {{show.hall.gold_price}}
        <hr>
      </div>
      <div class="mycontainer">
        <hr>
          &nbsp; &nbsp; <input type="radio" name="type_radio" value="Silver">
          &nbsp; &nbsp; &nbsp; &nbsp; Silver tickets:
          &nbsp; &nbsp; &nbsp; &nbsp; Total: {{show.hall.silver_no}}
          &nbsp; &nbsp; &nbsp; &nbsp; Left: {{show.silver_left}}
          &nbsp; &nbsp; &nbsp; &nbsp; Price: {{show.hall.silver_price}}
        <hr>
      </div>
      <strong>
          <label for="no_of_ticket">
            Choose How many tickets you want (upto 10 tickets can be bought at one time): &nbsp; &nbsp; 
          </label>
      </strong>
      <input type="number" name="no_of_ticket" min="1" max="10" placeholder="0"> <br> <br>
      <div class="center">
        <input type="submit" value="Calculate Amount" class="btn btn-success centerbutton">
      </div>
    </form>

    {% endif %}

    <hr>
    <hr>
  </div>  

{% endblock %}

BookMyShowClone/templates/movie_app/signup.html
{% extends 'base.html' %}

{% block content %}
    <hr>
        <div class="jumbotron">
            <h1>Sign Up</h1>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <br><br>
                <input type="submit" value="Sign Up" class="btn btn-outline-success btn-sm">
            </form>
        </div>
{% endblock %}