BookMyShowClone/BookMyShowClone/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views as main_views
from movie_app import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    path('', main_views.HomePage.as_view(), name = 'home'),
    path("signup/", views.SignUp.as_view(), name="signup"),
    path('thanks/', main_views.Thanks.as_view(), name = 'thanks'),
    path('admin/', admin.site.urls),
    path("movies/", include("movie_app.urls")),
    path("movies/", include("django.contrib.auth.urls")),
    path("logout/", views.user_logout, name="logout"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

BookMyShowClone/movie_app/urls.py
from django.urls import path
from . import views

app_name = 'movie_app'

urlpatterns = [
    path('NotEnough/', views.NotEnough.as_view(), name="NotEnough"),
    path('shows/', views.MovieListView, name = 'current_shows'),
    path('shows/<int:pk>/', views.show_times, name='movie_shows'),
    path('shows/<int:pk>/book', views.show_seats, name='seats'),
    path('shows/<int:pk>/payments', views.payments, name = 'payments'),
    path('my_tickets/', views.booked_tickets, name='my_tickets'),
    path("login/", views.Loginview, name='login'),
]

BookMyShowClone/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/master.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'movie_app/extras.css' %}">
</head>
<body style="background-image: repeating-linear-gradient(135deg, #101410, #143770);">
    <hr>
    {% if user.is_authenticated %}
      <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'movie_app:current_shows' %}">Current Movies</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'movie_app:my_tickets' %}">My Tickets</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Location
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Guwahati</a>
              <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Other locations</a>
              </div>
            </li>
            {% if user.is_staff %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">DataBase</a>
              </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
            </li>
          </ul>
        </div>
      </nav>
      </div>
    {% endif %}

    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

BookMyShowClone/templates/index.html
{% extends 'base.html' %}

{% block content %}
<hr>
  {% if user.is_authenticated %}
    <div class="mycontent">
      <h5>Your account was not logged out properly last time!!!</h5>
      <hr>
      <a class="btn btn-outline-danger btn-lg" href="{% url 'logout' %}">Log Out first!</a>
    </div>
  {% else %}
  <div class="jumbotron">
    <h1>Welcome!!!</h1> <br>
    <strong>
      <p>
        This is an example of a website that let's you book tickets for current 
        movies at any hall near you. Advanced booking feature is not impleamented so 
        you will only be able to book tickets for today's shows.
      </p>
      <hr>
    </strong>
    <h2>If you are new to the website Sign up here:</h2>
    <a class="btn btn-outline-primary btn-sm" href="{% url 'signup' %}">Sign Up</a>
    <br><br>
    <h3>Already have an account? Log In here:</h3>
    <a  class="btn btn-outline-primary btn-sm" href="{% url 'movie_app:login' %}">Log In</a>
  </div>
  {% endif %} 
{% endblock %}

BookMyShowClone/templates/thanks.html
{% extends "base.html" %}

{% block content %}
  <hr>
  <strong style="color:aliceblue;"><h4>Thanks!!!</h4></strong>

  <hr>
  <a class="btn btn-info" href="{% url 'movie_app:login' %}">Log Back In!</a> &nbsp; &nbsp;
  <a class="btn btn-info" href="{% url 'signup' %}">Sign Up with a different Account!</a>
  <hr>
{% endblock %}